collections:
  locations:
    output: true

defaults:
  - scope:
      path: ""
      type: "locations"
    values:
      layout: "location"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "empty"

baseurl: '/coffee'